/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion;

import controladores.JugadoresJpaController;
import controladores.UsuariosJpaController;
import entidades.Jugadores;
import entidades.Usuarios;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import javax.swing.JComboBox;

/**
 *
 * @author samuel
 */
public class AniadirJugador extends javax.swing.JFrame {

    UsuariosJpaController ujc = new UsuariosJpaController();
    JugadoresJpaController jjc = new JugadoresJpaController();

    /**
     * Creates new form AniadirJugador
     */
    public AniadirJugador() {
        initComponents();
        cargarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuario = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        campoApodo = new javax.swing.JTextField();
        campoSistema = new javax.swing.JTextField();
        radioDM = new javax.swing.JRadioButton();
        radioPJ = new javax.swing.JRadioButton();
        btnAniadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("APODO:");

        jLabel2.setText("SISTEMA:");

        jLabel3.setText("ROL:");

        jScrollPane1.setViewportView(listaUsuario);

        jLabel4.setText("JUGADOR ASOCIADO:");

        radioDM.setText("DM");
        radioDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDMActionPerformed(evt);
            }
        });

        radioPJ.setText("PJ");
        radioPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPJActionPerformed(evt);
            }
        });

        btnAniadir.setText("AÑADIR");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioDM)
                                .addGap(18, 18, 18)
                                .addComponent(radioPJ))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(campoApodo, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(btnAniadir)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addComponent(campoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(radioDM)
                    .addComponent(radioPJ))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(64, 64, 64)
                .addComponent(btnAniadir)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDMActionPerformed
        if (radioDM.isSelected()) {
            radioPJ.setSelected(false);
        }
    }//GEN-LAST:event_radioDMActionPerformed

    private void radioPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPJActionPerformed
        // TODO add your handling code here:
        if (radioPJ.isSelected()) {
            radioDM.setSelected(false);
        }
    }//GEN-LAST:event_radioPJActionPerformed

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        // TODO add your handling code here:
        String rolPreferido = radioDM.isSelected() ? "DM" : "PJ";
        Jugadores j = new Jugadores();
        j.setApodo(campoApodo.getText());
        j.setSistemaPredilecto(campoSistema.getText());
        j.setRolPreferido(rolPreferido);
        String nombre = listaUsuario.getSelectedValue();
        Usuarios user = ujc.findUsuariosEntities()
                .stream()
                .filter(u -> u.getNombre().equalsIgnoreCase(nombre))
                .findFirst()
                .get();

        user.setCodUsuario(j.getId());

        jjc.create(j);

        j.setCodUsuario(user);
        user.setJugador(j);
    }//GEN-LAST:event_btnAniadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AniadirJugador().setVisible(true);
            }
        });
    }

    private void cargarUsuario() {
        List<Usuarios> usuarios = ujc.findUsuariosEntities();
        List<String> nombres = usuarios.stream().map(Usuarios::getNombre).collect(Collectors.toList());

        // Convertir la lista de nombres a un arreglo
        String[] lista = nombres.toArray(new String[0]);

        // Cargar la lista en el JComboBox
        JComboBox<String> comboBox = new JComboBox<>(lista);

        // Asignar el JComboBox a tu control Swing
        // Por ejemplo, si tu control se llama "comboBoxUsuarios", puedes hacer:
        listaUsuario.setModel(comboBox.getModel());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoApodo;
    private javax.swing.JTextField campoSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaUsuario;
    private javax.swing.JRadioButton radioDM;
    private javax.swing.JRadioButton radioPJ;
    // End of variables declaration//GEN-END:variables
}
