/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import controladores.JugadoresJpaController;
import controladores.UsuariosJpaController;
import entidades.Jugadores;
import entidades.Usuarios;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author samuel
 */
public class AniadirJugador extends javax.swing.JFrame {

    UsuariosJpaController ujc = new UsuariosJpaController();
    JugadoresJpaController jjc = new JugadoresJpaController();

    /**
     * Creates new form AniadirJugador
     */
    public AniadirJugador() {
        comprobarUsuariosLibres();
        initComponents();
        cargarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuario = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        campoApodo = new javax.swing.JTextField();
        campoSistema = new javax.swing.JTextField();
        radioDM = new javax.swing.JRadioButton();
        radioPJ = new javax.swing.JRadioButton();
        btnAniadir = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AÑADIR JUGADOR");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APODO:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 125, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 188, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ROL:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 240, -1, -1));

        jScrollPane1.setViewportView(listaUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 283, 273, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JUGADOR ASOCIADO:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 283, -1, -1));
        getContentPane().add(campoApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 123, 166, -1));
        getContentPane().add(campoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 184, 166, -1));

        radioDM.setBackground(new java.awt.Color(255, 255, 255));
        radioDM.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        radioDM.setForeground(new java.awt.Color(0, 0, 0));
        radioDM.setText("DM");
        radioDM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        radioDM.setBorderPainted(true);
        radioDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDMActionPerformed(evt);
            }
        });
        getContentPane().add(radioDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 236, -1, -1));

        radioPJ.setBackground(new java.awt.Color(255, 255, 255));
        radioPJ.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        radioPJ.setForeground(new java.awt.Color(0, 0, 0));
        radioPJ.setText("PJ");
        radioPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        radioPJ.setBorderPainted(true);
        radioPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPJActionPerformed(evt);
            }
        });
        getContentPane().add(radioPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 236, -1, -1));

        btnAniadir.setText("AÑADIR");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 478, -1, -1));

        btnRecargar.setText("RECARGAR");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMenuAniadirJugador.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDMActionPerformed
        if (radioDM.isSelected()) {
            radioPJ.setSelected(false);
        }
    }//GEN-LAST:event_radioDMActionPerformed

    private void radioPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPJActionPerformed
        // TODO add your handling code here:
        if (radioPJ.isSelected()) {
            radioDM.setSelected(false);
        }
    }//GEN-LAST:event_radioPJActionPerformed

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        // TODO add your handling code here:
        String rolPreferido = radioDM.isSelected() ? "DM" : "PJ";
        Jugadores j = new Jugadores();
        j.setApodo(campoApodo.getText());
        j.setSistemaPredilecto(campoSistema.getText());
        j.setRolPreferido(rolPreferido);
        String nombre = listaUsuario.getSelectedValue();
        Usuarios user = ujc.findUsuariosEntities()
                .stream()
                .filter(u -> u.getNombre().equalsIgnoreCase(nombre))
                .findFirst()
                .get();

        j.setCodUsuario(user);
        jjc.create(j);

        user.setJugador(j);
        user.setCodUsuario(j.getId());

    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        cargarUsuario();
    }//GEN-LAST:event_btnRecargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AniadirJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AniadirJugador().setVisible(true);
            }
        });
    }

    private void cargarUsuario() {
        List<Usuarios> usuarios = ujc.findUsuariosEntities();
        List<String> nombres = usuarios.stream().filter(u -> u.getJugador() == null).map(Usuarios::getNombre).collect(Collectors.toList());

        // Convertir la lista de nombres a un arreglo
        String[] lista = nombres.toArray(new String[0]);

        // Cargar la lista en el JComboBox
        JComboBox<String> comboBox = new JComboBox<>(lista);

        // Asignar el JComboBox a tu control Swing
        // Por ejemplo, si tu control se llama "comboBoxUsuarios", puedes hacer:
        listaUsuario.setModel(comboBox.getModel());

    }

    private void comprobarUsuariosLibres() {
        if (ujc.findUsuariosEntities().stream().filter(u -> u.getJugador() == null).count() == 0) {
            JOptionPane.showMessageDialog(null, "No hay usuarios sin perfil de jugador asociado.\nCree un nuevo Usuario para continuar");

            this.dispose();

            java.awt.EventQueue.invokeLater(() -> {
                new AniadirUsuario().setVisible(true);
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnRecargar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoApodo;
    private javax.swing.JTextField campoSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaUsuario;
    private javax.swing.JRadioButton radioDM;
    private javax.swing.JRadioButton radioPJ;
    // End of variables declaration//GEN-END:variables
}
