/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import controladores.JugadoresJpaController;
import controladores.PersonajesJpaController;
import entidades.Jugadores;
import entidades.Personajes;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JComboBox;

/**
 *
 * @author sajm <sjimmaz322 at sjimmaz322@g.educaand.es>
 */
public class AniadirPersonaje extends javax.swing.JFrame {

    PersonajesJpaController pjc = new PersonajesJpaController();
    JugadoresJpaController jjc = new JugadoresJpaController();

    /**
     * Creates new form AniadirPersonaje
     */
    public AniadirPersonaje() {
        initComponents();
        cargarJugadores();
        quitarScrollLateral();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAniadir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoTrasfondo = new javax.swing.JTextArea();
        campoNombre = new javax.swing.JTextField();
        campoArquetipo = new javax.swing.JTextField();
        campoNivel = new javax.swing.JTextField();
        campoAlineacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AÑADIR PERSONAJE");
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(listaJugadores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 470, 100));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ARQUETIPO");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRASFONDO");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIVEL");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALINEACIÓN");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        btnAniadir.setText("AÑADIR");
        btnAniadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        campoTrasfondo.setColumns(20);
        campoTrasfondo.setRows(5);
        jScrollPane2.setViewportView(campoTrasfondo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 390, -1));
        getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 390, -1));
        getContentPane().add(campoArquetipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 390, -1));
        getContentPane().add(campoNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 80, -1));
        getContentPane().add(campoAlineacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 390, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JUGADORES");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoAniadirPersonaje.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        // TODO add your handling code here:
        Personajes p = new Personajes();
        p.setNombre(campoNombre.getText());
        p.setArquetipo(campoArquetipo.getText());
        p.setTrasfondo(campoTrasfondo.getText());
        p.setNivel(Integer.valueOf(campoNivel.getText()));
        p.setAlineacion(campoAlineacion.getText());

        String nombre = listaJugadores.getSelectedValue();

        Jugadores j = jjc.findJugadoresEntities().stream()
                .filter(u -> u.getApodo().equalsIgnoreCase(nombre))
                .findFirst()
                .get();

        p.setIdJugador(j);

        pjc.create(p);


    }//GEN-LAST:event_btnAniadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AniadirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AniadirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AniadirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AniadirPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AniadirPersonaje().setVisible(true);
            }
        });
    }

    private void cargarJugadores() {
        List<Jugadores> jugadores = jjc.findJugadoresEntities();
        List<String> nombres = jugadores.stream().map(Jugadores::getApodo).collect(Collectors.toList());

        // Convertir la lista de nombres a un arreglo
        String[] lista = nombres.toArray(String[]::new);

        // Cargar la lista en el JComboBox
        JComboBox<String> comboBox = new JComboBox<>(lista);

        // Asignar el JComboBox a tu control Swing
        // Por ejemplo, si tu control se llama "comboBoxUsuarios", puedes hacer:
        listaJugadores.setModel(comboBox.getModel());
    }

    private void quitarScrollLateral() {
        campoTrasfondo.setLineWrap(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton btnAniadir;
    private javax.swing.JTextField campoAlineacion;
    private javax.swing.JTextField campoArquetipo;
    private javax.swing.JTextField campoNivel;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextArea campoTrasfondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaJugadores;
    // End of variables declaration//GEN-END:variables
}
