/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import controladores.JugadoresJpaController;
import entidades.Jugadores;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sajm <sjimmaz322 at sjimmaz322@g.educaand.es>
 */
public class EdicionJugador extends javax.swing.JFrame {

    private int valor;
    JugadoresJpaController jjc = new JugadoresJpaController();

    /**
     * Creates new form EdicionJugador
     */
    public EdicionJugador() {
        initComponents();
    }

    public EdicionJugador(int valor) {
        this.valor = valor;
        initComponents();
        cargarValores();
    }

    private void cargarValores() {
        Jugadores u = jjc.findJugadores(valor);
        //JOptionPane.showMessageDialog(null, u);
        campoApodo.setText(u.getApodo());
        campoSistema.setText(u.getSistemaPredilecto());
        if (u.getRolPreferido().equalsIgnoreCase("DM")) {
            rDM.setSelected(true);
        } else {
            rPJ.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        campoApodo = new javax.swing.JTextField();
        campoSistema = new javax.swing.JTextField();
        rDM = new javax.swing.JRadioButton();
        rPJ = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDICIÓN DE JUGADOR");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("APODO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel3.setText("SISTEMA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel4.setText("ROL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));
        getContentPane().add(campoApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 140, -1));
        getContentPane().add(campoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 140, -1));

        rDM.setText("DM");
        rDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDMActionPerformed(evt);
            }
        });
        getContentPane().add(rDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        rPJ.setText("PJ");
        rPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPJActionPerformed(evt);
            }
        });
        getContentPane().add(rPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoEditar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDMActionPerformed
        // TODO add your handling code here:
        rPJ.setSelected(false);
    }//GEN-LAST:event_rDMActionPerformed

    private void rPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPJActionPerformed
        // TODO add your handling code here:
        rDM.setSelected(false);
    }//GEN-LAST:event_rPJActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        Jugadores u = jjc.findJugadores(valor);
        u.setApodo(campoApodo.getText());
        u.setSistemaPredilecto(campoSistema.getText());
        if (rDM.isSelected()) {
            u.setRolPreferido("DM");
        } else if (rPJ.isSelected()) {
            u.setRolPreferido("PJ");
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una de las opciones proporcionadas");
        }

        try {
            jjc.edit(u);
            JOptionPane.showMessageDialog(null, "Jugador modificado con éxito");
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(EdicionJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdicionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdicionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdicionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdicionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoApodo;
    private javax.swing.JTextField campoSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rDM;
    private javax.swing.JRadioButton rPJ;
    // End of variables declaration//GEN-END:variables
}
