/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import controladores.JugadoresJpaController;
import controladores.PersonajesJpaController;
import entidades.Jugadores;
import entidades.Personajes;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sajm <sjimmaz322 at sjimmaz322@g.educaand.es>
 */
public class MenuEditarPersonaje extends javax.swing.JFrame {

    JugadoresJpaController jjc = new JugadoresJpaController();
    PersonajesJpaController pjc = new PersonajesJpaController();

    /**
     * Creates new form MenuEditarPersonaje
     */
    public MenuEditarPersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rId = new javax.swing.JRadioButton();
        rNombre = new javax.swing.JRadioButton();
        rNivel = new javax.swing.JRadioButton();
        rJugador = new javax.swing.JRadioButton();
        rArquetipo = new javax.swing.JRadioButton();
        campoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPersonajes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDICIÓN DE PERSONAJE");
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rId.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rId.setForeground(new java.awt.Color(255, 255, 255));
        rId.setText("ID");
        getContentPane().add(rId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        rNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rNombre.setForeground(new java.awt.Color(255, 255, 255));
        rNombre.setText("NOMBRE");
        getContentPane().add(rNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        rNivel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rNivel.setForeground(new java.awt.Color(255, 255, 255));
        rNivel.setText("NIVEL");
        getContentPane().add(rNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        rJugador.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rJugador.setForeground(new java.awt.Color(255, 255, 255));
        rJugador.setText("JUGADOR");
        getContentPane().add(rJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        rArquetipo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rArquetipo.setForeground(new java.awt.Color(255, 255, 255));
        rArquetipo.setText("ARQUETIPO");
        getContentPane().add(rArquetipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));
        getContentPane().add(campoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 220, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR POR:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        btnModificar.setText("MODIFICAR");
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));

        jScrollPane2.setViewportView(listaPersonajes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoEditar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String campo = campoTxt.getText();
        List<Jugadores> jugadores = jjc.findJugadoresEntities();
        if (rId.isSelected()) {

        } else if (rNombre.isSelected()) {

        } else if (rNivel.isSelected()) {

        } else if (rArquetipo.isSelected()) {

        } else if (rJugador.isSelected()) {

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una de las opciones dadas");
        }
        List<String> nombres = jugadores.stream().map(Jugadores::getApodo).collect(Collectors.toList());

        // Convertir la lista de nombres a un arreglo
        String[] lista = nombres.toArray(String[]::new);

        // Cargar la lista en el JComboBox
        JComboBox<String> comboBox = new JComboBox<>(lista);

        // Asignar el JComboBox a tu control Swing
        // Por ejemplo, si tu control se llama "comboBoxUsuarios", puedes hacer:
        listaPersonajes.setModel(comboBox.getModel());

        //Añadimos el modelo a nuestra tabla para que se muestre la información
        //Añadimos el modelo a nuestra tabla para que se muestre la información

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEditarPersonaje().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPersonajes;
    private javax.swing.JRadioButton rArquetipo;
    private javax.swing.JRadioButton rId;
    private javax.swing.JRadioButton rJugador;
    private javax.swing.JRadioButton rNivel;
    private javax.swing.JRadioButton rNombre;
    // End of variables declaration//GEN-END:variables
}
