/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import controladores.PersonajesJpaController;
import entidades.Personajes;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sajm <sjimmaz322 at sjimmaz322@g.educaand.es>
 */
public class MenuEditarPersonaje extends javax.swing.JFrame {

    PersonajesJpaController pjc = new PersonajesJpaController();
    public static int code;

    /**
     * Creates new form MenuEditarPersonaje
     */
    public MenuEditarPersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rId = new javax.swing.JRadioButton();
        rNombre = new javax.swing.JRadioButton();
        rNivel = new javax.swing.JRadioButton();
        rJugador = new javax.swing.JRadioButton();
        rArquetipo = new javax.swing.JRadioButton();
        campoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContenidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDICIÓN DE PERSONAJE");
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rId.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rId.setForeground(new java.awt.Color(0, 0, 0));
        rId.setText("ID");
        rId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rIdActionPerformed(evt);
            }
        });
        getContentPane().add(rId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        rNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rNombre.setForeground(new java.awt.Color(0, 0, 0));
        rNombre.setText("NOMBRE");
        rNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNombreActionPerformed(evt);
            }
        });
        getContentPane().add(rNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        rNivel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rNivel.setForeground(new java.awt.Color(0, 0, 0));
        rNivel.setText("NIVEL");
        rNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNivelActionPerformed(evt);
            }
        });
        getContentPane().add(rNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        rJugador.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rJugador.setForeground(new java.awt.Color(0, 0, 0));
        rJugador.setText("JUGADOR");
        rJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(rJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        rArquetipo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rArquetipo.setForeground(new java.awt.Color(0, 0, 0));
        rArquetipo.setText("ARQUETIPO");
        rArquetipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rArquetipoActionPerformed(evt);
            }
        });
        getContentPane().add(rArquetipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));
        getContentPane().add(campoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 220, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR POR:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, -1));

        tablaContenidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaContenidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 540, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoEditar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dfm = new DefaultTableModel() {
            //Evitamos que las celdas sean modificables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        List<Personajes> pjs;
        //Creamos una cabecera
        String[] cabecera = {"ID", "NOMBRE", "ARQUETIPO", "NIVEL", "ALINEACION", "JUGADOR"};
        //Añadimos la cabecera a la tabla
        dfm.setColumnIdentifiers(cabecera);

        List<Personajes> lista = pjc.findPersonajesEntities();
        if (rId.isSelected()) {
            pjs = lista.stream().filter(p -> Objects.equals(p.getId(), Integer.valueOf(campoTxt.getText()))).toList();
            if (!pjs.isEmpty()) {
                for (Personajes p : pjs) {
                    try {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), p.getIdJugador().getApodo()};

                        dfm.addRow(o);
                    } catch (NullPointerException npe) {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), "Sin jugador asociado"};

                        dfm.addRow(o);
                    }
                }
            }

        } else if (rNombre.isSelected()) {
            pjs = lista.stream().filter(p -> p.getNombre().equalsIgnoreCase(campoTxt.getText())).toList();
            if (!pjs.isEmpty()) {
                for (Personajes p : pjs) {
                    try {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), p.getIdJugador().getApodo()};

                        dfm.addRow(o);
                    } catch (NullPointerException npe) {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), "Sin jugador asociado"};

                        dfm.addRow(o);
                    }
                }
            }
        } else if (rNivel.isSelected()) {
            pjs = lista.stream().filter(p -> (p.getNivel() == Integer.valueOf(campoTxt.getText()))).toList();
            if (!pjs.isEmpty()) {
                for (Personajes p : pjs) {
                    try {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), p.getIdJugador().getApodo()};

                        dfm.addRow(o);
                    } catch (NullPointerException npe) {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), "Sin jugador asociado"};

                        dfm.addRow(o);
                    }
                }
            }
        } else if (rArquetipo.isSelected()) {
            pjs = lista.stream().filter(p -> p.getArquetipo().equalsIgnoreCase(campoTxt.getText())).toList();
            if (!pjs.isEmpty()) {
                for (Personajes p : pjs) {
                    try {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), p.getIdJugador().getApodo()};

                        dfm.addRow(o);
                    } catch (NullPointerException npe) {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), "Sin jugador asociado"};

                        dfm.addRow(o);
                    }
                }
            }
        } else if (rJugador.isSelected()) {
            pjs = lista.stream().filter(p -> p.getIdJugador().getApodo().equalsIgnoreCase(campoTxt.getText())).toList();
            if (!pjs.isEmpty()) {
                for (Personajes p : pjs) {
                    try {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), p.getIdJugador().getApodo()};

                        dfm.addRow(o);
                    } catch (NullPointerException npe) {
                        Object[] o = {p.getId(), p.getNombre(), p.getArquetipo(), p.getNivel(), p.getAlineacion(), "Sin jugador asociado"};

                        dfm.addRow(o);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una de las opciones dadas");
        }

        tablaContenidos.setModel(dfm);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rIdActionPerformed
        // TODO add your handling code here:
        rArquetipo.setSelected(false);
        rNombre.setSelected(false);
        rNivel.setSelected(false);
        rJugador.setSelected(false);
    }//GEN-LAST:event_rIdActionPerformed

    private void rNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNombreActionPerformed
        // TODO add your handling code here:
        rArquetipo.setSelected(false);
        rNivel.setSelected(false);
        rJugador.setSelected(false);
        rId.setSelected(false);
    }//GEN-LAST:event_rNombreActionPerformed

    private void rNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNivelActionPerformed
        // TODO add your handling code here:
        rArquetipo.setSelected(false);
        rNombre.setSelected(false);
        rJugador.setSelected(false);
        rId.setSelected(false);
    }//GEN-LAST:event_rNivelActionPerformed

    private void rArquetipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rArquetipoActionPerformed
        // TODO add your handling code here:
        rNombre.setSelected(false);
        rNivel.setSelected(false);
        rJugador.setSelected(false);
        rId.setSelected(false);
    }//GEN-LAST:event_rArquetipoActionPerformed

    private void rJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rJugadorActionPerformed
        // TODO add your handling code here:
        rArquetipo.setSelected(false);
        rNombre.setSelected(false);
        rNivel.setSelected(false);
        rId.setSelected(false);
    }//GEN-LAST:event_rJugadorActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        int filaSeleccionada = tablaContenidos.getSelectedRow();
        int valor = (int) tablaContenidos.getValueAt(filaSeleccionada, 0);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdicionPJ(valor).setVisible(true);
            }
        });
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEditarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEditarPersonaje().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField campoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rArquetipo;
    private javax.swing.JRadioButton rId;
    private javax.swing.JRadioButton rJugador;
    private javax.swing.JRadioButton rNivel;
    private javax.swing.JRadioButton rNombre;
    private javax.swing.JTable tablaContenidos;
    // End of variables declaration//GEN-END:variables
}
